### ISSUE TITLE
New maintainer half added?

### ISSUE THREAD

**Issue by MatthewHambley** [conda-forge/sci-fab-feedstock#4]
@conda-forge/core 

I used the proscribed method for adding a new maintainer, the PR was raised and I committed it. Unfortunately the new maintainer missed the invitation e-mail from GitHub and new appears to be only half added.

Your bots are (presumably) aware of her existence but she has not been added to the GitHub project.

I tried resubmitting the addition request but it's smart enough to know it's done it already. What should I try next?

**Comment by dopplershift** [comment]
@conda-forge-admin please update team

**Comment by dopplershift** [comment]
Looks like that successfully resent the invitation.

**Comment by MatthewHambley** [comment]
That seems to have worked. Thanks for your help.
